name: thanks
on:
  workflow_dispatch:
jobs:
  thanks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            const issue_number = context.issue.number || 1;
            console.log(`issue_number: ${issue_number} for ${context.repo.owner}/${context.repo.repo}`);
